using System.Runtime.CompilerServices;

namespace NEvo.CodeAnalysis.Analysing.Extracting.Code;

public class NonAutoGeneratedTypeArtifactFilter : IClassArtifactFilter
{
    public bool IsValidCodeArtifact(Type type) =>
        !type.IsAutoClass
        && !type.GetCustomAttributes(true).OfType<CompilerGeneratedAttribute>().Any()
        && !(type is { IsSealed: true, IsNestedPrivate: true } && type.GetInterfaces().Contains(typeof(IAsyncStateMachine)));
}
