apiVersion: v1
kind: Service
metadata:
    name: ext-sql-server
spec:
    ports:
    - port: 1433
  
#---
# apiVersion: v1
# kind: Endpoints
#metadata:
#  name: ext-sql-server
#subsets:
#  - addresses:
#        - ip: 127.0.0.1
#    ports:
#      - port: 1433