version: '3.4'

services:
  choirmanagement.membership.webservice:
    image: ${DOCKER_REGISTRY-}choirmanagementmembershipwebservice
    build:
      context: .
      dockerfile: src/ChoirManagement.Membership.WebService/Dockerfile
    ports:
      - "8001:80"

  choirmanagement.accounting.webservice:
    image: ${DOCKER_REGISTRY-}choirmanagementaccountingwebservice
    build:
      context: .
      dockerfile: src/ChoirManagement.Accounting.WebService/Dockerfile
    ports:
      - "8002:80"


